In [2]:
import numpy as np 

In [5]:
#Program 1  "Create a 3 x 3 numpy array of all True (Boolean)"
arr3x3 = np.ones((3,3),dtype=bool)
print(arr3x3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
#Program 2 "Get the common items from arr1 and arr2"

arr1 = np.array([1,2,4,6,8,95,3])
arr2 = np.array([5,78,6,1,7,5,3])

intersection = np.intersect1d(arr1,arr2)
print("Intesection : ",intersection)


Intesection :  [1 3 6]


In [19]:
#Program 3 "Swap Rows 1 and 2 in the array"
arr2D = np.random.randint(1,10,size=(3,5))
print("Before swapping 0th and 1st row \n",arr2D)
arr2D[[0,1]] = arr2D[[1,0]]
print("After swapping 0th and 1st row : \n",arr2D)

Before swapping 0th and 1st row 
 [[6 5 1 6 1]
 [6 2 2 9 9]
 [1 2 3 3 6]]
After swapping 0th and 1st row : 
 [[6 2 2 9 9]
 [6 5 1 6 1]
 [1 2 3 3 6]]


In [29]:
#Program 4 " Reverse the columns of a 2D array "
import numpy as np
arr=np.array([2,4,889,66,8,10,12])
print("Array before Reversing  : \n",arr)
print(arr)
rev=np.flip(arr)
print("Array after swapping columns : \n",rev)

Array before Reversing  : 
 [  2   4 889  66   8  10  12]
[  2   4 889  66   8  10  12]
Array after swapping columns : 
 [ 12  10   8  66 889   4   2]


In [22]:
#program 5 (show only 3 decimal places numpy array )
num=np.round(np.random.normal(0.121,4.567,10),3)
print(num)

[  4.18    4.819  -9.978 -13.139  -4.276  -3.798  -4.161  -1.521  -8.7
   4.6    -7.528  -5.548  -2.885   1.552  -1.165   3.906   4.87   -5.662
  -3.008   7.088   3.271   2.408   7.962   5.23   -0.354   1.878   1.448
  -3.372   0.337   5.262   7.38    0.817  -8.489  -0.073]


In [30]:
#Program 6 "Compute Mean Median standard deviation of an array"
print("Mean of:",arr, "is",np.mean(arr))
print("Median of ",arr," is ", np.median(arr))
print("Standard deviation of ",arr," is ", np.std(arr))


Mean of: [  2   4 889  66   8  10  12] is 141.57142857142858
Median of  [  2   4 889  66   8  10  12]  is  10.0
Standard deviation of  [  2   4 889  66   8  10  12]  is  305.8262144901705
