In [1]:
import numpy as np 
import pandas as pd

In [2]:
#Program 1  "Create a 3 x 3 numpy array of all True (Boolean)"
arr3x3 = np.ones((3,3),dtype=bool)
print(arr3x3)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
#Program 2 "Get the common items from arr1 and arr2"

arr1 = np.array([1,2,4,6,8,95,3])
arr2 = np.array([5,78,6,1,7,5,3])

intersection = np.intersect1d(arr1,arr2)
print("Intesection : ",intersection)


Intesection :  [1 3 6]


In [4]:
#Program 3 "Swap Rows 1 and 2 in the array"
arr2D = np.random.randint(1,10,size=(3,5))
print("Before swapping 0th and 1st row \n",arr2D)
arr2D[[0,1]] = arr2D[[1,0]]
print("After swapping 0th and 1st row : \n",arr2D)

Before swapping 0th and 1st row 
 [[1 1 5 1 6]
 [9 7 5 3 8]
 [5 5 7 5 8]]
After swapping 0th and 1st row : 
 [[9 7 5 3 8]
 [1 1 5 1 6]
 [5 5 7 5 8]]


In [5]:
#Program 4 " Reverse the columns of a 2D array "
import numpy as np
arr=np.array([2,4,889,66,8,10,12])
print("Array before Reversing  : \n",arr)
print(arr)
rev=np.flip(arr)
print("Array after swapping columns : \n",rev)

Array before Reversing  : 
 [  2   4 889  66   8  10  12]
[  2   4 889  66   8  10  12]
Array after swapping columns : 
 [ 12  10   8  66 889   4   2]


In [6]:
#program 5 (show only 3 decimal places numpy array )
num=np.round(np.random.normal(0.121,4.567,10),3)
print(num)

[-1.301  2.827 -2.295  1.023 -0.539  6.051  0.716  7.837  5.984 -0.329]


In [7]:
#Program 6 "Compute Mean Median standard deviation of an array"
print("Mean of:",arr, "is",np.mean(arr))
print("Median of ",arr," is ", np.median(arr))
print("Standard deviation of ",arr," is ", np.std(arr))


Mean of: [  2   4 889  66   8  10  12] is 141.57142857142858
Median of  [  2   4 889  66   8  10  12]  is  10.0
Standard deviation of  [  2   4 889  66   8  10  12]  is  305.8262144901705


In [9]:
users = pd.read_csv(r"C:\Users\om\Downloads\username.csv",sep=";",index_col=0)
print(users)


            Identifier First name Last name
Username                                   
booker12          9012     Rachel    Booker
grey07            2070      Laura      Grey
johnson81         4081      Craig   Johnson
jenkins46         9346       Mary   Jenkins
smith79           5079      Jamie     Smith
