In [3]:
import numpy as np 
import pandas as pd

In [4]:
#Program 1  "Create a 3 x 3 numpy array of all True (Boolean)"
arr3x3 = np.ones((3,3),dtype=bool)
print(arr3x3)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
#Program 2 "Get the common items from arr1 and arr2"

arr1 = np.array([1,2,4,6,8,95,3])
arr2 = np.array([5,78,6,1,7,5,3])

intersection = np.intersect1d(arr1,arr2)
print("Intesection : ",intersection)


Intesection :  [1 3 6]


In [6]:
#Program 3 "Swap Rows 1 and 2 in the array"
arr2D = np.random.randint(1,10,size=(3,5))
print("Before swapping 0th and 1st row \n",arr2D)
arr2D[[0,1]] = arr2D[[1,0]]
print("After swapping 0th and 1st row : \n",arr2D)

Before swapping 0th and 1st row 
 [[3 5 9 1 7]
 [8 5 1 9 5]
 [8 8 6 9 3]]
After swapping 0th and 1st row : 
 [[8 5 1 9 5]
 [3 5 9 1 7]
 [8 8 6 9 3]]


In [7]:
#Program 4 " Reverse the columns of a 2D array "
import numpy as np
arr=np.array([2,4,889,66,8,10,12])
print("Array before Reversing  : \n",arr)
print(arr)
rev=np.flip(arr)
print("Array after swapping columns : \n",rev)

Array before Reversing  : 
 [  2   4 889  66   8  10  12]
[  2   4 889  66   8  10  12]
Array after swapping columns : 
 [ 12  10   8  66 889   4   2]


In [8]:
#program 5 (show only 3 decimal places numpy array )
num=np.round(np.random.normal(0.121,4.567,10),3)
print(num)

[-0.729  8.189 10.812  0.945  1.639  0.391 -0.222 -4.434 -0.38   1.567]


In [9]:
#Program 6 "Compute Mean Median standard deviation of an array"
print("Mean of:",arr, "is",np.mean(arr))
print("Median of ",arr," is ", np.median(arr))
print("Standard deviation of ",arr," is ", np.std(arr))


Mean of: [  2   4 889  66   8  10  12] is 141.57142857142858
Median of  [  2   4 889  66   8  10  12]  is  10.0
Standard deviation of  [  2   4 889  66   8  10  12]  is  305.8262144901705


In [10]:
users = pd.read_csv(r"C:\Users\om\Downloads\username.csv",sep=";",index_col=0)
print(users)


FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\om\\Downloads\\username.csv'

In [17]:
csv_olympics=pd.read_csv(r"/home/om/Downloads/olympics1.csv")
oly_df=pd.DataFrame(csv_olympics)
oly_df["totalgoldcount"] = oly_df["Gold"]+oly_df["Gold.1"] 
print(oly_df["totalgoldcount"])

0       0
1       5
2      18
3       1
4       3
       ..
141    26
142     0
143     0
144     3
145     8
Name: totalgoldcount, Length: 146, dtype: int64
